export const KPI_DICTIONARY = [
  { kpi: "Paid Orders", definition: "Shopify orders with a non-empty Paid at date or a paid / partially refunded financial status.", formula: "Count distinct Shopify orders where Paid at is not empty, excluding cancelled-before-payment rows.", source: "Shopify Orders export", columns: "Name / Id, Paid at, Financial Status, Cancelled at", owner: "CS / Shopify", frequency: "Weekly + Monthly" },
  { kpi: "Tickets / Order", definition: "Customer support contact rate against paid orders.", formula: "Actionable Gorgias tickets / Paid Shopify orders", source: "Gorgias tickets or overview + Shopify orders", columns: "Ticket id, Assignee name, Paid at", owner: "Customer Service", frequency: "Weekly + Monthly" },
  { kpi: "CSAT", definition: "Average customer satisfaction score from Gorgias surveys.", formula: "Average Survey score responses", source: "Gorgias Customer Experience / tickets export", columns: "Survey score / CSAT", owner: "Customer Service", frequency: "Weekly + Monthly" },
  { kpi: "SLA / Response Time", definition: "Average first response time or SLA metric available in the export.", formula: "Weighted average first response time when agent-level data exists; otherwise Customer Experience export value", source: "Gorgias Customer Experience + Agents metrics", columns: "First response time, SLA", owner: "Customer Service", frequency: "Weekly + Monthly" },
  { kpi: "Automation Rate", definition: "Share of support workload handled by Notch automation.", formula: "AI handled / total actionable tickets. Placeholder until Notch export is uploaded.", source: "Notch export / Gorgias AI intent data", columns: "AI solved, Total tickets", owner: "Automation", frequency: "Monthly" },
  { kpi: "AI Cost / Order", definition: "Real Notch cost per paid order.", formula: "Notch invoice total / Paid Shopify orders", source: "Notch invoices + Shopify orders", columns: "Invoice total, Paid orders", owner: "Finance / CS", frequency: "Monthly" },
  { kpi: "Human CS Cost / Order", definition: "Human customer service cost per paid order.", formula: "Canada message cost + Philippines invoice total / Paid Shopify orders", source: "Canada message pricing + VA Academy invoices + Shopify orders", columns: "Messages sent, invoice totals, Paid orders", owner: "Finance / CS", frequency: "Monthly" },
  { kpi: "Total CX Cost / Order", definition: "Total customer experience operating cost per paid order.", formula: "(Human CS cost + Notch AI cost) / Paid Shopify orders", source: "Finance invoices + Shopify orders", columns: "Costs, Paid orders", owner: "Finance / CS", frequency: "Monthly" },
  { kpi: "Refund Rate", definition: "Share of paid orders that are refunded or partially refunded.", formula: "Refunded paid orders / Paid orders", source: "Shopify Orders export", columns: "Financial Status, Refunded Amount, Total", owner: "Operations / Finance", frequency: "Monthly" },
  { kpi: "Cancellation Rate", definition: "Share of total Shopify orders cancelled.", formula: "Cancelled orders / Total orders", source: "Shopify Orders export", columns: "Cancelled at, Cancel Reason, Financial Status", owner: "Operations", frequency: "Monthly" },
  { kpi: "Fraud Orders", definition: "Orders identified as fraud using Shopify risk/fraud/cancel reason fields when present.", formula: "Count orders where risk/cancel reason/tags contain fraud", source: "Shopify Orders export", columns: "Risk Level, Cancel Reason, Tags", owner: "Operations", frequency: "Monthly" }
];
